name: Run Tests

on:
  push:
    branches: [ main ]
    paths:
# this ensures that tests are run when adding new tests or packages
      - 'tests/**'
      - 'validation_packages/**'
      - '.github/**'
  pull_request:
    branches: [ main ]
    paths:
# here, also run tests when a pr targets source files
      - 'tests/**'
      - 'validation_packages/**'
      - '.github/**'

jobs:
  build-and-test:
    name: "Build and test"
    uses: nfdi4plants/actions-workflows/.github/workflows/build-and-test-solution.yml@main
    with:
      solution: ./arc-validation-packages.sln
      checkout-submodules: true
      configuration: Release